# all units are in millimeters

# the default configuration is for a 2 liter bottle

# the height of the legs, this should be above the 
# water level (lowest inlet) + bottle_depth to ensure 
# a siphon is established when water levels drop.
leg_height = 75 #was 150
# the camber of the legs in degrees. This 
# should be a small angle that lowers center 
# of mass while not significantly reducing height.
leg_camber = 15
wall_thickness = 5
# the diameter of the narrowest part of the bottle 
# that will rest in the cusp of the stand
nozzle_diameter = 85 # was 35 40 because why not
# the depth of the nozzle section of the bottle
nozzle_depth = 20
# the diameter of the bottle that is a cylinder 
# (not the slope from the nozzle)
bottle_diameter = 104
# the depth of the body of the bottle
bottle_depth = 25