# all units are in millimeters

# the height of the legs, this should be above the 
# water level (lowest inlet) + bottle_depth
leg_height = 150
# the camber of the legs in degrees. This 
# should be a small angle that lowers center 
# of mass while not significantly reducing height.
leg_camber = 15
wall_thickness = 5
# the diameter of the bottle that is a cylinder 
# (not the slope from the nozzle)
bottle_diameter = 104
# the depth of the nozzle of the bottle
bottle_depth = 104