# due to issues with powershell, enter this command to render each object inside each module directory
# example is for mount, replace mount with the file generated by ./render.ps1
& 'C:\Program Files\OpenSCAD\openscad.exe' -o mount.stl mount.scad
