#!/bin/bash
# a bash script that goes through all python module directories and renders the file using the config file

# we will render the following:
# Carbon_Filter # DO NOT RENDER NOT COMPLETE
# Inlet
# Nozzle_Array
# Refracting_Nozzle_Junctions #DO NOT RENDER NOT PART OF CURRENT TEST DESIGN
# Reservoir
# Spill_Guard
# Tube_Linkage #DO NOT RENDER NOT COMPLETE
# Water_Bracket

#RENDER:
cd Inlet && python3 Inlet.py && cd .. &
cd Nozzle_Array && python3 Nozzle_Array.py && cd .. &
cd Reservoir && python3 Bottle_Stand.py && cd .. &
cd Spill_Guard && python3 Spill_Guard.py && cd .. &
cd Tube_Linkage && python3 Tube_Linkage.py && cd .. &
cd Water_Bracket && python3 Water_Bracket.py && cd .. &