# Inlet Flange
# all measurements are in millimeters

# the radius of the bucket or other container
# container_radius = 135
# height of the inlet solution (for the bucket this is all hole along all the bands)
# above the first half of the first hole since this will be the spout and catch.
#inlet_height = 100
container_top_radius = 151.25
container_bottom_radius = 131.2
container_height = 355.6
guard_height = 88.9

#the slope of the cone that will make a water tight seal against the radius of the inlet
#cone_slope = 45 #degrees

# since we use 1" diameter drill bit this is the radius:
radius = 12.66

# distance between the outer cone in the inner cone that is to set how many thread turns
# until the cones pinch against the container to fasten the outer inlet to the inner inlet
# this should be the wall thickness of the container
fastner_gap = 2 #TODO: for some reason this is larger in the model

#thread parameters
#TODO: butt threads (sawtooth profile) from mcad
#the resoluion of the thread profile
thread_resolution = 1000
#the number of complete revolutions of the thread
thread_count = 5
#the total length of the thread
thread_span = 12.66
#the depth of the threaded insert profile, should be less than wall_thickness TODO: but there is an error in the design
thread_depth = 2
#the height of the threaded insert profile
#set to negative and positive to set the buttress rising edge
thread_length = -1

#NOTE: this is subtractive so high values will increase pressure loss by this amount. essentially
#radius is now radius-wall_thickness when calculating total area of the sum of inlets to equate
#the fans total area.
wall_thickness = 3.25

flange_thickness = 7 #must be greater than wall thickness TODO: make this additive to wall thickness in scad
