# Spill Guard
# all measurements are in millimeters

# the radius of the bucket or other container
# container_radius = 135
# height of the inlet solution (for the bucket this is all hole along all the bands)
# above the first half of the first hole since this will be the spout and catch.
#inlet_height = 100
container_top_radius = 151.25
container_bottom_radius = 131.2
container_height = 355.6
guard_height = 88.9
# distance to shroud from container at the top of the shroud
# this and inlet height determine shroud_angle. This is used to ensure pressure 
# loss doesnt occur due to venturi choke.
shroud_distance = 50
# since we use 1" diameter drill bit this is the radius:
radius = 12.66
# the thickness of the bucket
clip_gap = 2.35
# the depth the clips will sit
clip_depth = 11
wall_thickness = 4
