# Water Cooling Bracket Mount
# configure the bracket by entering a list of lists for each screw position
# besides that this is a standard parametric design. 
# measurements are in millimiters

# TODO: make a well documented excel sheet that is read in as CSV 
#       with dynamic params as a seperate column
# TODO: or consider a tkinter GUI with photogrammetry for thingiverse. 
#       assume kids (age 10+) will want these too.
# TODO: recreate am4 for just a water block

# NOTE: TOML only allows for positional arguments-- 
#       so make iterable args positional and leave template documentation

# NOTE: current configuration is for a water-peltier cooling cube 

# ALUMINUM WATER BLOCK MEASUREMENTS #
# actual measurements-- not from datsheet due to compounding error with print accuracy.
# measurements seem consistent across order/manufacturing run, verify over time.
# consider lowering by a fraction of a millimeter to press down on dye
# NOTE: z is 11.85 but lowered to set pressure on dye
# ORIGINAL #
# rectangle_prism_dimensions = "[43, 43, 10]" #for non cube standard 40mm water block
rectangle_prism_dimensions = "[71.4, 71.4, 0.75]"
# can be (1,0) (0,-1) etc. avoid diagonal: (-1, 1)
# nozzle_direction =  "(-1,0)" #for non cube standard 40mm water block
nozzle_direction = "(0,0)" #we dont use outlets on the prism since this thing is huge

wall_thickness = 2

#determines whether we will use through holes for screws like CPUs or pagoda fasteners like chipsets.
is_pagoda = "False"
#the radius of the pagoda cone that will snap through the hole mounts. ignored if is_pagoda is false.
pagdoda_thickness = 1

# SCREW MOBO MEASUREMENTS #
# if using standard water block set z to 0
screw_args = '''
[
{"x": -27.09, "y": 45, "z": -41, "screw_head_diameter": 7.15, "screw_bolt_diameter": 3.42,"screw_bolt_depth":  11.8}, 
{"x": -27.09, "y": -45, "z": -41, "screw_head_diameter": 7.15, "screw_bolt_diameter": 3.42,"screw_bolt_depth":  11.8}, 
{"x": 27.09, "y": -45, "z": -41, "screw_head_diameter": 7.15, "screw_bolt_diameter": 3.42,"screw_bolt_depth":  11.8}, 
{"x": 27.09, "y": 45, "z": -41, "screw_head_diameter": 7.15, "screw_bolt_diameter": 3.42,"screw_bolt_depth":  11.8},
]'''
