# Water Cooling Bracket Mount
# configure the bracket by entering a list of lists for each screw position
# besides that this is a standard parametric design. 
# measurements are in millimiters

# TODO: make a well documented excel sheet that is read in as CSV 
#       with dynamic params as a seperate column
# TODO: or consider a tkinter GUI with photogrammetry for thingiverse. 
#       assume kids (age 10+) will want these too.
# TODO: recreate am4 for just a water block

# NOTE: TOML only allows for positional arguments-- 
#       so make iterable args positional and leave template documentation

# NOTE: current configuration is for a water-peltier cooling cube 

# ALUMINUM WATER BLOCK MEASUREMENTS #
# ORIGINAL #
# AM4 MEASUREMENTS:
rectangle_prism_dimensions = "[43, 43, 10]" #for non cube standard 40mm water block
# PROJECT AL MEASUREMENTS:
# rectangle_prism_dimensions = "[71.4, 71.4, 0.75]"
# can be (1,0) (0,-1) etc. avoid diagonal: (-1, 1)

# AM4 MEASUREMENTS:
nozzle_direction =  "(-1,0)" #for non cube standard 40mm water block
# PROJECT AL MEASUREMENTS:
# nozzle_direction = "(0,0)" #we dont use outlets on the prism since this thing is huge

wall_thickness = 2

#determines whether we will use through holes for screws like CPUs or pagoda fasteners like chipsets.
is_pagoda = "False"
#the radius of the pagoda cone that will snap through the hole mounts. ignored if is_pagoda is false.
pagdoda_thickness = 1

# SCREW MOBO MEASUREMENTS #
# TODO: currently these can only have negative or zero z values
# MI25 with 40mm water block
#TODO: MI25 also needs screws set to m4 kit purchased (dont use a washer.. just set here)
#NOTE: was z=0 moved lower due to thread count not being high enough
screw_args = '''
[
{"x": -32.1840, "y": 32.1840, "z": -2, "screw_head_diameter": 7.15, "screw_bolt_diameter": 3.42,"screw_bolt_depth":  11.8}, 
{"x": -32.1840, "y": -32.1840, "z": -2, "screw_head_diameter": 7.15, "screw_bolt_diameter": 3.42,"screw_bolt_depth":  11.8}, 
{"x": 32.1840, "y": -32.1840, "z": -2, "screw_head_diameter": 7.15, "screw_bolt_diameter": 3.42,"screw_bolt_depth":  11.8}, 
{"x": 32.1840, "y": 32.1840, "z": -2, "screw_head_diameter": 7.15, "screw_bolt_diameter": 3.42,"screw_bolt_depth":  11.8},
]'''

# PROJECT AL MEASUREMENTS:
# screw_args = '''
# [
# {"x": -25.7109, "y": 42.7091, "z": -41, "screw_head_diameter": 7.15, "screw_bolt_diameter": 3.42,"screw_bolt_depth":  11.8}, 
# {"x": 25.7109, "y": -42.7091, "z": -41, "screw_head_diameter": 7.15, "screw_bolt_diameter": 3.42,"screw_bolt_depth":  11.8}, 
# ]'''
