# Water Cooling Bracket Mount
# configure the bracket by entering a list of lists for each screw position
# besides that this is a standard parametric design. 
# measurements are in millimiters

# TODO: make a well documented excel sheet that is read in as CSV 
#       with dynamic params as a seperate column
# TODO: or consider a tkinter GUI with photogrammetry for thingiverse. 
#       assume kids (age 10+) will want these too.

# NOTE: TOML only allows for positional arguments-- 
#       so make iterable args positional and leave template documentation

# ALUMINUM WATER BLOCK MEASUREMENTS #
rectangle_prism_dimensions = "[43, 43, 10]"
# can be (1,0) (0,-1) diagonal: (-1, 1) etc.
nozzle_direction =  "(-1,0)"
wall_thickness = 2

# SCREW MOBO MEASUREMENTS #
screw_args = '''
[
    {"x": -25, "y": -25, "z": 0, "screw_head_diameter": 5.95, "screw_bolt_diameter": 1.33,"screw_bolt_depth":  4},
    {"x": 25, "y": -25, "z": 0, "screw_head_diameter": 5.95, "screw_bolt_diameter": 1.33,"screw_bolt_depth":  4},
    {"x": 25, "y": 25, "z": 0, "screw_head_diameter": 5.95, "screw_bolt_diameter": 1.33,"screw_bolt_depth":  4},
    {"x": -25, "y": 25, "z": 0, "screw_head_diameter": 5.95, "screw_bolt_diameter": 1.33,"screw_bolt_depth":  4},
]'''

