#76.2 initial_radius
#114.3 final_radius
#was 152.4
# NOTE: support gussets on white lid are 135mm
# leaves outer area for support.

# all entries are in millimeters.
# TODO: try smaller layer heights(currently 0.2). Effectively underextrudes for 
#	better resolution in the case of small geometries
#	test flow of sample for further analysis. need sufficient 
#	pressure through array sequence since negating tube_wall_thickness

# initial_radius = 94
initial_radius = 80
#final_radius = 115 #was 135
final_radius = 135 #was 135
nozzle_diameter = 2 #0.8
nozzle_wall_thickness = 1
drop_down_depth = 8

max_segment_size = 150
# PVC tube inteconnect diameter between nozzle arrays
tube_diameter = 7.6 # was 8 was 7.8
# thickness of the expanding cone to grip the tube
pagoda_thickness = 1.5 # was 1.8

# wall_thickness = 4.5
wall_thickness = 2.5
array_spacing = 10
