# all entries are in millimeters.
initial_radius = 76.2
final_radius = 140
nozzle_diameter = 1.75
nozzle_wall_thickness = 1
drop_down_depth = 8
max_segment_size = 150
tube_diameter = 8
wall_thickness = 10
tube_wall_thickness = 1.25
