# all entries are in millimeters #
# These configuration values are set for a 5 gallon bucket RepVap #
# it is recommended to reinforce the fastener cones and inlets with 
# super glue to ensure they dont break due to layer adhesion tolerances.

#LID PARAMETERS#
# initial_radius = 94
initial_radius = 80
final_radius = 135

#NOZZLE PARAMETERS#
#nozzle_diameter = 1.25
nozzle_diameter = 0.75
nozzle_wall_thickness = 2
nozzle_track_spacing = 2

#LID INTERFACE PARAMETERS#
# drop down depth helps decrease the pressure at each nozzle and can help 
# ensure the entire array is filled with water for a given pump.
drop_down_depth = 1
max_segment_size = 150
array_spacing = 5 #concentric distance between arrays

#INTERCONNECT PARAMETERS#
# flexible tube inteconnect diameter between nozzle arrays
#tube_diameter = 7.6
tube_diameter = 7.4
# thickness of the expanding cone to grip the tube
inlet_thickness = 1.3 # was 1.8

#LID FASTENER PARAMETERS#
#the distance the fastener will travel 
#(thickness of the lid of the container)
fastener_gap = 4
#the diameter of the hole
# fastener_thickness = 4.7
fastener_diameter = 6.35
fastener_diameter = 8.00
#the diameter of the cone that will snap in the hole
# fastener_diameter = 6.25

#OBJECT PARAMETERS#
wall_thickness = 4.5

epsilon = 0.1